### ISSUE TITLE
Crash upon entering world

### ISSUE THREAD

**Issue by nocturni** [tesseract4d/Better-Portals#1]
i just installed the mod, loaded it and it instantly crashes

java.lang.IllegalAccessError: tried to access field net.minecraft.entity.Entity.field_71087_bX from class mods.tesseract.betterportals.BetterPortals
	at mods.tesseract.betterportals.BetterPortals.onLivingUpdtaeEvent(BetterPortals.java:33)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_37_BetterPortals_onLivingUpdtaeEvent_LivingUpdateEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:581)
	at net.minecraft.entity.EntityLivingBase.onUpdate(EntityLivingBase.java:2095)
	at net.minecraft.entity.player.EntityPlayer.onUpdate(EntityPlayer.java:234)
	at net.minecraft.entity.player.EntityPlayerMP.onUpdateEntity(EntityPlayerMP.java:382)
	at net.minecraft.network.NetHandlerPlayServer.update(NetHandlerPlayServer.java:173)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.update(NetworkDispatcher.java:209)
	at net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:285)
	at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:790)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:279)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:1817)
	at java.lang.Thread.run(Unknown Source)

**Comment by TesseractLHY** [comment]
Somehow everything works properly in my development environment so I didn't noticed it.
Now I just fixed it,you can get the latest version from the github releases.

**Comment by nocturni** [comment]
thanks a bunch for looking into it! seems to work well

i had a feature to request, would it be possible to make the overworld portal thingy optional?

**Comment by TesseractLHY** [comment]
Now I add a configuration which allows you to disable return portal and gateway portal,lastest version has been released.

**Comment by nocturni** [comment]
thank you so much!
